on: 
  workflow_dispatch:
    inputs:
      ZD_TOKEN:
        description: 'ZD token'     
        required: true
        type: string

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      # workato only supports Python 3.9+
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

      # we should not install any other deps since Workato doesn't support it
      # copy&paste the source code if you really need it
  log-the-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python test.py
        env:
          ZD_TOKEN: ${{ inputs.ZD_TOKEN }}
          TAGS: ${{ inputs.tags }}
          ENVIRONMENT: ${{ inputs.environment }}