on: 
  workflow_dispatch:
    inputs:
      ZD_TOKEN:
        description: 'ZD token'     
        required: true
        type: string
      WAIT_PERIOD_SECONDS:
        description: 'WAIT PERIODS'     
        required: true
        type: string
        default: '10'
      MAX_RETRY_TIMES:
        description: 'MAX RETRY TIMES'     
        required: true
        type: string
        default: '5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      # workato only supports Python 3.9+
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: run E2E
      run: |
        python test.py
      env:
        ZD_TOKEN: ${{ inputs.ZD_TOKEN }}